- name: Make sure snmpd package is installed
  apt: pkg={{item}} state=installed
  with_items:
    - snmpd
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Make sure snmpd package is installed
  yum: pkg={{item}} state=installed
  with_items:
    - net-snmp
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Copy snmpd Config
  template:
    src=snmpd.conf.j2
    dest=/etc/snmp/snmpd.conf
    owner=root
    group=root
    mode=0600

- name: Enable and restart snmpd
  service: name=snmpd enabled=true state=restarted 